# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /code/CMakeFiles /code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ebur128

# Build rule for target.
ebur128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ebur128
.PHONY : ebur128

# fast build rule for target.
ebur128/fast:
	$(MAKE) -f CMakeFiles/ebur128.dir/build.make CMakeFiles/ebur128.dir/build
.PHONY : ebur128/fast

#=============================================================================
# Target rules for targets named expat

# Build rule for target.
expat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expat
.PHONY : expat

# fast build rule for target.
expat/fast:
	$(MAKE) -f CMakeFiles/expat.dir/build.make CMakeFiles/expat.dir/build
.PHONY : expat/fast

#=============================================================================
# Target rules for targets named faac

# Build rule for target.
faac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faac
.PHONY : faac

# fast build rule for target.
faac/fast:
	$(MAKE) -f CMakeFiles/faac.dir/build.make CMakeFiles/faac.dir/build
.PHONY : faac/fast

#=============================================================================
# Target rules for targets named fdkaac

# Build rule for target.
fdkaac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdkaac
.PHONY : fdkaac

# fast build rule for target.
fdkaac/fast:
	$(MAKE) -f CMakeFiles/fdkaac.dir/build.make CMakeFiles/fdkaac.dir/build
.PHONY : fdkaac/fast

#=============================================================================
# Target rules for targets named ffmpeg

# Build rule for target.
ffmpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffmpeg
.PHONY : ffmpeg

# fast build rule for target.
ffmpeg/fast:
	$(MAKE) -f CMakeFiles/ffmpeg.dir/build.make CMakeFiles/ffmpeg.dir/build
.PHONY : ffmpeg/fast

#=============================================================================
# Target rules for targets named fontconfig

# Build rule for target.
fontconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fontconfig
.PHONY : fontconfig

# fast build rule for target.
fontconfig/fast:
	$(MAKE) -f CMakeFiles/fontconfig.dir/build.make CMakeFiles/fontconfig.dir/build
.PHONY : fontconfig/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f CMakeFiles/freetype.dir/build.make CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named fribidi

# Build rule for target.
fribidi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fribidi
.PHONY : fribidi

# fast build rule for target.
fribidi/fast:
	$(MAKE) -f CMakeFiles/fribidi.dir/build.make CMakeFiles/fribidi.dir/build
.PHONY : fribidi/fast

#=============================================================================
# Target rules for targets named frmxtract

# Build rule for target.
frmxtract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frmxtract
.PHONY : frmxtract

# fast build rule for target.
frmxtract/fast:
	$(MAKE) -f CMakeFiles/frmxtract.dir/build.make CMakeFiles/frmxtract.dir/build
.PHONY : frmxtract/fast

#=============================================================================
# Target rules for targets named lame

# Build rule for target.
lame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lame
.PHONY : lame

# fast build rule for target.
lame/fast:
	$(MAKE) -f CMakeFiles/lame.dir/build.make CMakeFiles/lame.dir/build
.PHONY : lame/fast

#=============================================================================
# Target rules for targets named libass

# Build rule for target.
libass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libass
.PHONY : libass

# fast build rule for target.
libass/fast:
	$(MAKE) -f CMakeFiles/libass.dir/build.make CMakeFiles/libass.dir/build
.PHONY : libass/fast

#=============================================================================
# Target rules for targets named libogg

# Build rule for target.
libogg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libogg
.PHONY : libogg

# fast build rule for target.
libogg/fast:
	$(MAKE) -f CMakeFiles/libogg.dir/build.make CMakeFiles/libogg.dir/build
.PHONY : libogg/fast

#=============================================================================
# Target rules for targets named libpng

# Build rule for target.
libpng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng
.PHONY : libpng

# fast build rule for target.
libpng/fast:
	$(MAKE) -f CMakeFiles/libpng.dir/build.make CMakeFiles/libpng.dir/build
.PHONY : libpng/fast

#=============================================================================
# Target rules for targets named libtheora

# Build rule for target.
libtheora: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtheora
.PHONY : libtheora

# fast build rule for target.
libtheora/fast:
	$(MAKE) -f CMakeFiles/libtheora.dir/build.make CMakeFiles/libtheora.dir/build
.PHONY : libtheora/fast

#=============================================================================
# Target rules for targets named libvorbis

# Build rule for target.
libvorbis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvorbis
.PHONY : libvorbis

# fast build rule for target.
libvorbis/fast:
	$(MAKE) -f CMakeFiles/libvorbis.dir/build.make CMakeFiles/libvorbis.dir/build
.PHONY : libvorbis/fast

#=============================================================================
# Target rules for targets named libvpx

# Build rule for target.
libvpx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvpx
.PHONY : libvpx

# fast build rule for target.
libvpx/fast:
	$(MAKE) -f CMakeFiles/libvpx.dir/build.make CMakeFiles/libvpx.dir/build
.PHONY : libvpx/fast

#=============================================================================
# Target rules for targets named opencore-amr

# Build rule for target.
opencore-amr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencore-amr
.PHONY : opencore-amr

# fast build rule for target.
opencore-amr/fast:
	$(MAKE) -f CMakeFiles/opencore-amr.dir/build.make CMakeFiles/opencore-amr.dir/build
.PHONY : opencore-amr/fast

#=============================================================================
# Target rules for targets named openssl

# Build rule for target.
openssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openssl
.PHONY : openssl

# fast build rule for target.
openssl/fast:
	$(MAKE) -f CMakeFiles/openssl.dir/build.make CMakeFiles/openssl.dir/build
.PHONY : openssl/fast

#=============================================================================
# Target rules for targets named opus

# Build rule for target.
opus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opus
.PHONY : opus

# fast build rule for target.
opus/fast:
	$(MAKE) -f CMakeFiles/opus.dir/build.make CMakeFiles/opus.dir/build
.PHONY : opus/fast

#=============================================================================
# Target rules for targets named rtmpdump

# Build rule for target.
rtmpdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmpdump
.PHONY : rtmpdump

# fast build rule for target.
rtmpdump/fast:
	$(MAKE) -f CMakeFiles/rtmpdump.dir/build.make CMakeFiles/rtmpdump.dir/build
.PHONY : rtmpdump/fast

#=============================================================================
# Target rules for targets named speex

# Build rule for target.
speex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 speex
.PHONY : speex

# fast build rule for target.
speex/fast:
	$(MAKE) -f CMakeFiles/speex.dir/build.make CMakeFiles/speex.dir/build
.PHONY : speex/fast

#=============================================================================
# Target rules for targets named x264

# Build rule for target.
x264: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x264
.PHONY : x264

# fast build rule for target.
x264/fast:
	$(MAKE) -f CMakeFiles/x264.dir/build.make CMakeFiles/x264.dir/build
.PHONY : x264/fast

#=============================================================================
# Target rules for targets named x265

# Build rule for target.
x265: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x265
.PHONY : x265

# fast build rule for target.
x265/fast:
	$(MAKE) -f CMakeFiles/x265.dir/build.make CMakeFiles/x265.dir/build
.PHONY : x265/fast

#=============================================================================
# Target rules for targets named xvidcore

# Build rule for target.
xvidcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xvidcore
.PHONY : xvidcore

# fast build rule for target.
xvidcore/fast:
	$(MAKE) -f CMakeFiles/xvidcore.dir/build.make CMakeFiles/xvidcore.dir/build
.PHONY : xvidcore/fast

#=============================================================================
# Target rules for targets named yasm

# Build rule for target.
yasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yasm
.PHONY : yasm

# fast build rule for target.
yasm/fast:
	$(MAKE) -f CMakeFiles/yasm.dir/build.make CMakeFiles/yasm.dir/build
.PHONY : yasm/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f CMakeFiles/zlib.dir/build.make CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... libvpx"
	@echo "... fontconfig"
	@echo "... opus"
	@echo "... libpng"
	@echo "... ffmpeg"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xvidcore"
	@echo "... libvorbis"
	@echo "... zlib"
	@echo "... ebur128"
	@echo "... speex"
	@echo "... fdkaac"
	@echo "... libass"
	@echo "... frmxtract"
	@echo "... expat"
	@echo "... yasm"
	@echo "... rtmpdump"
	@echo "... libtheora"
	@echo "... openssl"
	@echo "... faac"
	@echo "... libogg"
	@echo "... freetype"
	@echo "... opencore-amr"
	@echo "... fribidi"
	@echo "... lame"
	@echo "... x264"
	@echo "... x265"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

